from __future__ import annotations

import numpy as np
from scipy import signal


def detect_r_peaks(ecg_filtered: np.ndarray, fs: int, min_distance_s: float = 0.28) -> np.ndarray:
    """Detect R-peaks using adaptive peak detection.

    The method is intentionally simple and deterministic for engineering demos.
    It works well on the synthetic data generated by this project and on many
    clean single-lead ECG examples.
    """

    x = np.asarray(ecg_filtered, dtype=float)
    if x.size == 0:
        return np.array([], dtype=int)

    # Standardize robustly.
    mad = np.median(np.abs(x - np.median(x))) + 1e-8
    z = (x - np.median(x)) / (1.4826 * mad)

    # Emphasize QRS-like spikes with a short moving average of squared amplitude.
    envelope = z**2
    kernel_len = max(1, int(0.06 * fs))
    kernel = np.ones(kernel_len) / kernel_len
    smooth = np.convolve(envelope, kernel, mode="same")

    distance = max(1, int(min_distance_s * fs))
    height = max(float(np.percentile(smooth, 80)), float(np.mean(smooth) + 0.6 * np.std(smooth)))
    candidate_peaks, _ = signal.find_peaks(smooth, distance=distance, height=height)

    if len(candidate_peaks) == 0:
        # Fallback: directly detect positive peaks.
        height_raw = max(float(np.percentile(z, 92)), 1.5)
        peaks, _ = signal.find_peaks(z, distance=distance, height=height_raw)
        return peaks.astype(int)

    # Refine each candidate to the maximum absolute ECG sample in a small local window.
    refined: list[int] = []
    half = max(1, int(0.06 * fs))
    for peak in candidate_peaks:
        start = max(0, peak - half)
        end = min(len(x), peak + half + 1)
        local = start + int(np.argmax(x[start:end]))
        refined.append(local)

    refined_arr = np.unique(np.array(refined, dtype=int))
    if len(refined_arr) <= 1:
        return refined_arr

    # Remove peaks that are too close after refinement by keeping the stronger one.
    keep: list[int] = []
    for p in refined_arr:
        if not keep or p - keep[-1] >= distance:
            keep.append(int(p))
        elif abs(x[p]) > abs(x[keep[-1]]):
            keep[-1] = int(p)
    return np.array(keep, dtype=int)


def rr_intervals_from_peaks(r_peaks: np.ndarray, fs: int) -> np.ndarray:
    if len(r_peaks) < 2:
        return np.array([], dtype=float)
    return np.diff(r_peaks) / fs
